#!/usr/bin/env python
# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-

import sys
import os,getopt,multiprocessing

from speech import __version__
from speech.conf import Conf, LISTLANG
from speech.textutils import adaptTextToDict

conf = Conf()

def printHelp():
    print('%s version %s' % (conf.app_name, __version__))
    print('')
    print('Usage : %s-cli -i " [text to read]" ( or -f [txt file] ) -o [.wav filename] ... -l [optional lang]' %\
            conf.app_name)
    print('')
    print('Common flags:')
    print(' -h   --help                   show usage information')
    print('      --version                show version information')
    print(' -i   --input-text             text to read')
    print(' -f   --input-file             file to read (supported only plain txt')
    print(' -o   --output-file            name of the audio output file (wav type)')
    print(' -l   --lang                   language')
    print('possible languages:')
    for l in LISTLANG:
        print( l )

#read text file
def text_file(filename):
    try:
        f = open(filename, 'r')
    except IOError:
        return "Error: file not found"
    return f.read()

if __name__ == "__main__":

    try:
        opts, args = getopt.getopt(sys.argv[1:], "hvi:f:l:o:", ["help", "version",\
                "input-text=","input-file", "lang=", "output-file="])
    except getopt.GetoptError:
        printHelp()
        sys.exit(2)

    input_file = ""
    text = ""

    for opt, arg in opts:
        if opt in ('-h', '--help'):
            printHelp()
            sys.exit()
        if opt in ('-v', '--version'):
            print('%s version %s' % (conf.app_name, __version__))
            sys.exit()
        
        if opt in ('-l', '--lang'):
            lang = arg
        elif opt in ('-o', '--output-file'):
            outfile = arg
        elif opt in ('-f', '--input-file'):
            input_file = arg
        elif opt in ('-i', '--input-text'):
            text = arg

    if lang in LISTLANG:
        conf.setLang(lang)

    if input_file:
        text = text_file( input_file )

    text = adaptTextToDict(conf.dict_path, text)
    if len(text) <= 32768:
        cmd = 'pico2wave -l %s -w %s \"%s\" ' % ( conf.lang,outfile, text )
        os.system(cmd)

    elif os.path.isfile('/usr/bin/sox'):
        discours = text.split('.')
        cmds = []
        names = []
        text = ''
        for idx,paragraph in enumerate(discours):
            text += paragraph
            if idx == len(discours)-1 or len(text) + len(discours[idx+1]) >= 32767:
                filename = conf.cache_path + 'speech' + str(idx) + '.wav'
                cmds.append('pico2wave -l %s -w %s \"%s\" ' % ( conf.lang, filename, text ))
                names.append(filename)
                text = ''

        nproc = int(.5 * multiprocessing.cpu_count())
        if nproc == 0:
            nproc = 1
        multiprocessing.Pool(nproc).map(os.system, cmds)
        os.system('sox %s %s' % ( ' '.join(names), outfile ))
        for fichier in names:
            os.remove(fichier)
