#!/usr/bin/python3

import sys
import os
from os.path import join, expanduser

from speech.debug import is_debug_mode
from speech.dic import replace

if __name__ == "__main__":
    if is_debug_mode():
        print('DEBUG MODE')
    if len(sys.argv) <= 1:
        print("il manque un argument pour le texte à lire")
        exit(0)
    if len(sys.argv) == 2:
        print("il manque un second argument pour le chemin du fichier son")
        exit(0)
    text = sys.argv[1]
    path = sys.argv[2]
    lang = 'fr-FR'
    CONF_DIR = '.'
    if not is_debug_mode():
        CONF_DIR = join(expanduser('~'), '.config/gSpeech')

    text = text.replace('\"', '')
    text = text.replace('`', '')
    text = text.replace('´', '')
    text = text.replace('-','')

    dict_path = CONF_DIR + '/' + lang + '.dic'
    text = replace(dict_path, text)
    if len(text) <= 32768:
        cmd = 'pico2wave -l %s -w %s \"%s\" ' % ( lang, path, text )
        if is_debug_mode():
            print(cmd)
        os.system(cmd)

    elif os.path.isfile('/usr/bin/sox'):
        discours = text.split('\n\n')
        cmds = []
        names = []
        text = ''
        for idx,paragraph in enumerate(discours):
            text += paragraph
            if idx == len(discours)-1 or len(text) + len(discours[idx+1]) >= 32767:
                filename = CACHEFOLDER + 'speech' + str(idx) + '.wav'
                cmds.append('pico2wave -l %s -w %s \"%s\" ' % ( lang, filename, text ))
                names.append(filename)
                text = ''

        nproc = int(.5 * multiprocessing.cpu_count())
        if nproc == 0:
            nproc = 1
        multiprocessing.Pool(nproc).map(os.system, cmds)
        os.system('sox %s %s' % ( ' '.join(names), path ))
        for fichier in names:
            os.remove(fichier)
